apiVersion: v1
kind: Service

metadata:
  name: novapay-service

  labels:
    app: novapay
    app.kubernetes.io/name: novapay
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: {{ .Values.service.type }}

  selector:
    app: novapay

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 4000
      nodePort: {{ .Values.service.nodePort }}
