name: novapay

services:
  novapay:
    container_name: novapay

    build:
      context: .
      dockerfile: Dockerfile

    image: novapay:latest

    restart: unless-stopped

    ports:
      - "4000:4000"

    env_file:
      - .env


