apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: novapay-ingress

spec:
  ingressClassName: nginx

  rules:
    - host: novapay.local

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: novapay-service

                port:
                  number: 4000
