import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, CreditCard, Home, Lock, LogOut, Menu, Send, Settings, Shield, User, Users, Wallet } from 'lucide-react';
import { dashboard, login, register, transfer } from './api.js';
import './styles.css';

const money = (n) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n);
function Auth({ onAuthed }) {
  const [mode, setMode] = useState('login'); const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); setError(''); const f = new FormData(e.currentTarget);
    try { const res = mode === 'login' ? await login(f.get('email'), f.get('password')) : await register({ name: f.get('name'), email: f.get('email'), password: f.get('password') }); localStorage.setItem('novapay_token', res.token); onAuthed(res.user); }
    catch (err) { setError(err.message); }
  }
  return <main className="auth-shell"><section className="auth-card"><div className="brand-mark"><Shield size={25}/></div><h1>NovaPay</h1><p>{mode === 'login' ? 'Welcome back! Sign in to your account' : 'Create your account and bank securely'}</p><form onSubmit={submit}>{mode === 'register' && <label>Full Name<input name="name" placeholder="Enter your full name" required /></label>}<label>Email<input name="email" type="email" placeholder="Enter your email" defaultValue="alok@novapay.com" required /></label><label>Password<input name="password" type="password" placeholder="Enter your password" defaultValue={mode === 'login' ? 'Password123!' : ''} minLength="8" required /></label>{error && <div className="error">{error}</div>}<button>{mode === 'login' ? 'Sign In' : 'Create Account'}</button></form><small>{mode === 'login' ? "Don't have an account?" : 'Already have an account?'} <a onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Sign up' : 'Sign in'}</a></small></section><section className="auth-art"><div className="phone"><Shield/><strong>NovaPay</strong><span>Secure • Fast • Reliable</span></div><ul><li><Lock size={16}/> Secure & encrypted</li><li><Send size={16}/> Fast transactions</li><li><Bell size={16}/> 24/7 alerts</li></ul></section></main>;
}
function Sidebar({ view, setView, logout }) { const items = [['dashboard', Home], ['wallets', Wallet], ['transactions', CreditCard], ['transfer', Send], ['beneficiaries', Users], ['profile', User], ['settings', Settings]]; return <aside className="sidebar"><h2><Shield/>NovaPay</h2>{items.map(([i, Icon]) => <button key={i} onClick={() => setView(i)} className={view === i ? 'active' : ''}><Icon size={16}/>{i}</button>)}<button onClick={logout}><LogOut size={16}/>logout</button></aside>; }
function App() { const [user, setUser] = useState(null); const [data, setData] = useState(null); const [view, setView] = useState('dashboard'); const [notice, setNotice] = useState('');
  useEffect(() => { if (localStorage.getItem('novapay_token')) dashboard().then((d) => { setData(d); setUser(d.user); }).catch(() => localStorage.removeItem('novapay_token')); }, []);
  const rows = data?.transactions ?? []; const max = Math.max(...(data?.chart ?? [1]));
  async function sendTransfer(e) { e.preventDefault(); const f = new FormData(e.currentTarget); const res = await transfer({ fromWalletId: f.get('wallet'), to: f.get('to'), amount: Number(f.get('amount')), description: f.get('description') }); setNotice(`Transfer completed: ${money(Math.abs(res.transaction.amount))}`); setData(await dashboard()); e.currentTarget.reset(); }
  if (!user) return <Auth onAuthed={(u) => { setUser(u); dashboard().then(setData); }} />;
  return <div className="app"><Sidebar view={view} setView={setView} logout={() => { localStorage.clear(); location.reload(); }}/><main className="content"><header><button className="hamb"><Menu/></button><div><h1>Welcome back, {user.name} 👋</h1><p>Here's what's happening with your account today.</p></div><Bell/><div className="avatar">AS</div></header>{notice && <div className="notice">{notice}</div>}
  {view === 'dashboard' && <><section className="stats">{[['Total Balance', data?.stats.totalBalance, 'blue'], ['Income', data?.stats.income, 'green'], ['Expenses', data?.stats.expenses, 'red'], ['Pending', data?.stats.pending, 'orange']].map(([l,v,c]) => <article className={c} key={l}><span>{l}</span><strong>{money(v||0)}</strong></article>)}</section><section className="grid"><article className="panel"><h3>Balance Overview</h3><div className="chart">{data?.chart.map((v,i)=><i key={i} style={{height:`${(v/max)*100}%`}} />)}</div></article><Transactions rows={rows.slice(0,5)} /></section><Actions setView={setView}/></>}
  {view === 'wallets' && <section className="panel"><h2>My Wallets</h2>{data?.wallets.map(w=><div className="wallet-row" key={w.id}><span className={w.color}><Wallet/></span><b>{w.name}</b><small>{w.maskedNumber}</small><strong>{money(w.balance)}</strong></div>)}</section>}
  {view === 'transfer' && <section className="grid"><article className="panel"><h2>Transfer Money</h2><form className="transfer" onSubmit={sendTransfer}><select name="wallet">{data?.wallets.map(w=><option key={w.id} value={w.id}>{w.name} ({money(w.balance)})</option>)}</select><input name="to" placeholder="Beneficiary name or account" required/><input name="amount" type="number" step="0.01" min="1" placeholder="Amount" required/><input name="description" placeholder="Description (optional)"/><button>Transfer Now</button></form></article><article className="panel"><h3>Recent Beneficiaries</h3>{data?.beneficiaries.map(b=><div className="beneficiary" key={b.id}><Users size={18}/><b>{b.name}</b><small>{b.account}</small></div>)}</article></section>}
  {view === 'transactions' && <Transactions rows={rows} full />}{!['dashboard','wallets','transfer','transactions'].includes(view) && <section className="panel"><h2>{view}</h2><p>Production-ready placeholder for the {view} module.</p></section>}</main></div> }
function Transactions({ rows, full }) { return <article className="panel"><h2>Transactions</h2><table><tbody>{rows.map(t=><tr key={t.id}><td>{new Date(t.date).toLocaleDateString()}</td><td>{t.description}</td>{full && <td>{t.type}</td>}<td className={t.amount>0?'pos':'neg'}>{money(t.amount)}</td><td><span className="pill">{t.status}</span></td></tr>)}</tbody></table></article>; }
function Actions({ setView }) { return <section className="actions"><button onClick={()=>setView('transfer')}><Send/>Send Money</button><button><Wallet/>Add Money</button><button><CreditCard/>Pay Bills</button><button><Bell/>Mobile Recharge</button></section>; }
createRoot(document.getElementById('root')).render(<App />);
export { Auth };
